# Generated by Django 4.0.6 on 2022-12-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_data', '0005_rename_traded_quantity_weeklydelivery_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True, verbose_name='BookMark Name')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookMarkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='stock add date to get price')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('book_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.bookmark')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_data.stock')),
            ],
        ),
    ]
