# Generated by Django 4.0.6 on 2022-12-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookMarkItem',
        ),
    ]
