# Generated by Django 4.0.6 on 2022-12-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0005_rename_traded_quantity_weeklydelivery_volume'),
        ('user_interface', '0002_delete_bookmarkitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMarkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='stock add date to get price')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.bookmark')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_data.stock')),
            ],
            options={
                'unique_together': {('stock', 'bookmark')},
            },
        ),
    ]
