# Generated by Django 4.0.6 on 2022-12-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=225, null=True, unique=True, verbose_name='Stock Symbol')),
                ('name', models.CharField(blank=True, max_length=225, null=True, unique=True, verbose_name='Stock Name')),
                ('industry_type', models.CharField(blank=True, max_length=225, null=True, unique=True, verbose_name='Industry Type')),
                ('token', models.IntegerField(blank=True, null=True, verbose_name='Angle Stock Token')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekHighLow52',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='52 Week High Price')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='52 Week Low Price')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_data.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('open_price', models.FloatField(blank=True, null=True, verbose_name='Open Price')),
                ('high_price', models.FloatField(blank=True, null=True, verbose_name='High Price')),
                ('low_price', models.FloatField(blank=True, null=True, verbose_name='Low Price')),
                ('close_price', models.FloatField(blank=True, null=True, verbose_name='Close Price')),
                ('avg_price', models.FloatField(blank=True, null=True, verbose_name='AVG Price')),
                ('delivery_per', models.FloatField(blank=True, null=True, verbose_name='Delivery Percentage %')),
                ('no_of_trade', models.IntegerField(blank=True, null=True, verbose_name='Number of Trade')),
                ('delivery_qty', models.IntegerField(blank=True, null=True, verbose_name='Delivery Quantity')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Traded Quantity')),
                ('trade_ratio', models.FloatField(blank=True, null=True, verbose_name='Trade Ratio')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_data.stock')),
            ],
            options={
                'unique_together': {('stock', 'delivery_date')},
            },
        ),
    ]
