# Generated by Django 4.0.6 on 2022-12-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0002_alter_stock_industry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_high',
            field=models.FloatField(blank=True, null=True, verbose_name='Delivery is High Of AVG'),
        ),
        migrations.CreateModel(
            name='WeeklyDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('delivery_per', models.FloatField(blank=True, null=True, verbose_name='Delivery Percentage')),
                ('traded_quantity', models.IntegerField(blank=True, null=True, verbose_name='Traded Quantity')),
                ('no_of_trade', models.IntegerField(blank=True, null=True, verbose_name='No Of Trade')),
                ('delivery_qty', models.IntegerField(blank=True, null=True, verbose_name='Delivery Quantity')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_data.stock')),
            ],
            options={
                'unique_together': {('stock', 'end_date')},
            },
        ),
    ]
