# Generated by Django 4.0.6 on 2022-12-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0004_weeklydelivery_delivery_high'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklydelivery',
            old_name='traded_quantity',
            new_name='volume',
        ),
    ]
